# Generated by Django 2.2 on 2019-04-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('labels', models.TextField()),
                ('margins', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chartitem',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.ChartTicker'),
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
