# Generated by Django 2.2 on 2019-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20190421_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitem',
            name='updown_item',
            field=models.CharField(max_length=10),
        ),
    ]
