# Generated by Django 2.2 on 2019-04-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20190421_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartticker',
            name='margins',
        ),
    ]
