# Generated by Django 2.2 on 2019-04-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_auto_20190425_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartItemRawData',
        ),
    ]
