# Generated by Django 2.2 on 2019-04-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_chartitemdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartitemdata',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chartitemdata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chartitemdata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chartitemdata',
            name='open',
            field=models.FloatField(),
        ),
    ]
