# Generated by Django 2.2 on 2019-04-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20190425_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartticker',
            name='full_name',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
